[versions]
# SLF4J releases: http://www.slf4j.org/news.html
slf4j = "2.0.7"

# Tomcat releases: https://tomcat.apache.org/whichversion.html
tomcat = "10.1.11"

[libraries]

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
tomcat-embedded = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat" }
